// Brands and model families for the Add Watch dropdowns.
// To add a brand or model, add it here (alphabetical order is applied automatically).
// People can still type any brand/model that isn't listed.

export const watchCatalog: Record<string, string[]> = {
  "A. Lange & Söhne": ["1815", "Datograph", "Lange 1", "Odysseus", "Saxonia", "Zeitwerk"],
  "Audemars Piguet": ["Code 11.59", "Royal Oak", "Royal Oak Chronograph", "Royal Oak Jumbo", "Royal Oak Offshore"],
  Awake: ["Mission to Earth", "Mission to Space"],
  Baltic: ["Aquascaphe", "Bicompax", "HMS 002", "MR01"],
  "Bell & Ross": ["BR 03", "BR 05", "BR-X5"],
  Blancpain: ["Fifty Fathoms", "Fifty Fathoms Bathyscaphe", "Villeret"],
  Breguet: ["Classique", "Marine", "Type XX"],
  Breitling: ["Avenger", "Chronomat", "Navitimer", "Premier", "Superocean", "Superocean Heritage", "Top Time"],
  Bulgari: ["Bulgari Bulgari", "Octo Finissimo", "Serpenti"],
  Cartier: ["Ballon Bleu", "Panthère", "Pasha", "Santos", "Santos-Dumont", "Tank Française", "Tank Louis", "Tank Must"],
  "Casio G-Shock": ["DW-5600", "GA-2100", "GMW-B5000", "MR-G"],
  Chopard: ["Alpine Eagle", "Happy Sport", "L.U.C", "Mille Miglia"],
  "Christopher Ward": ["C1", "C60 Trident", "C63 Sealander", "The Twelve"],
  Citizen: ["Eco-Drive", "Promaster", "Tsuyosa"],
  Doxa: ["SUB 200", "SUB 300", "SUB 300T"],
  "Echo/Neutra": ["Averau", "Rivanera"],
  "Furlan Marri": ["Disco Volante", "Mechaquartz", "Tasti Tondi"],
  "Girard-Perregaux": ["Laureato", "Laureato Absolute"],
  "Grand Seiko": ["Evolution 9", "Heritage", "Snowflake (SBGA211)", "Sport", "White Birch (SLGH005)"],
  "H. Moser & Cie": ["Endeavour", "Pioneer", "Streamliner"],
  Hamilton: ["Jazzmaster", "Khaki Aviation", "Khaki Field", "Khaki Field Mechanical", "Ventura"],
  Hermès: ["Arceau", "H08", "Heure H"],
  Hublot: ["Big Bang", "Classic Fusion", "Spirit of Big Bang"],
  IWC: ["Big Pilot", "Ingenieur", "Pilot's Watch", "Portofino", "Portugieser", "Aquatimer"],
  "Jaeger-LeCoultre": ["Master Control", "Polaris", "Reverso", "Rendez-Vous"],
  "Konstantin Chaykin": ["Joker", "Wristmon"],
  "Kurono Tokyo": ["Bunkyo", "Chronograph", "Grand Mori", "Toki"],
  Longines: ["Conquest", "HydroConquest", "Legend Diver", "Master Collection", "Spirit", "Spirit Flyback", "Spirit Zulu Time"],
  Mido: ["Commander", "Multifort", "Ocean Star"],
  Montblanc: ["1858", "Star Legacy", "TimeWalker"],
  Nomos: ["Ahoi", "Club", "Metro", "Orion", "Tangente"],
  Omega: ["Aqua Terra", "Constellation", "De Ville", "Railmaster", "Seamaster 300M", "Seamaster Planet Ocean", "Speedmaster Moonwatch", "Speedmaster Racing"],
  Oris: ["Aquis", "Big Crown Pointer Date", "Divers Sixty-Five", "ProPilot"],
  Panerai: ["Luminor", "Luminor Due", "Radiomir", "Submersible"],
  "Patek Philippe": ["Aquanaut", "Calatrava", "Complications", "Grand Complications", "Nautilus", "Twenty~4"],
  Rado: ["Captain Cook", "Centrix", "True Square"],
  "Richard Mille": ["RM 011", "RM 035", "RM 67-01"],
  Rolex: ["Air-King", "Cosmograph Daytona", "Datejust 36", "Datejust 41", "Day-Date 40", "Explorer", "Explorer II", "GMT-Master II", "Land-Dweller", "Oyster Perpetual", "Sea-Dweller", "Sky-Dweller", "Submariner", "Submariner Date", "Yacht-Master"],
  Seiko: ["5 Sports", "Alpinist", "Presage", "Prospex", "Prospex Turtle"],
  Serica: ["4512 Field Chronometer", "5303 Diver", "8315 Chronograph"],
  Sinn: ["104", "556", "EZM 3"],
  Swatch: ["MoonSwatch", "Scuba Fifty Fathoms", "Sistem51"],
  "TAG Heuer": ["Aquaracer", "Carrera", "Formula 1", "Monaco"],
  Tissot: ["Gentleman", "PRX", "Seastar", "Visodate"],
  Tudor: ["1926", "Black Bay", "Black Bay 54", "Black Bay 58", "Black Bay 58 GMT", "Black Bay Chrono", "Black Bay GMT", "Black Bay Pro", "Pelagos", "Pelagos 39", "Ranger", "Royal"],
  "Ulysse Nardin": ["Diver", "Freak", "Marine"],
  "Vacheron Constantin": ["Fiftysix", "Historiques 222", "Overseas", "Patrimony", "Traditionnelle"],
  Zenith: ["Chronomaster Original", "Chronomaster Sport", "Defy", "Pilot"],
  // Added from the luxury & microbrand brand reference (Oct 2026). Models can be typed in if not listed.
  "Credor": ["Eichi", "Linealight"],
  "Glashütte Original": ["PanoMaticLunar", "SeaQ", "Senator"],
  "Jaquet Droz": ["Grande Seconde", "Petite Heure Minute"],
  "Parmigiani Fleurier": ["Kalpa", "Tonda PF"],
  "Piaget": ["Altiplano", "Polo", "Polo 79"],
  "Roger Dubuis": ["Excalibur"],
  "Accutron": ["DNA", "Spaceview"],
  "Airain": [],
  "Alpina": ["Alpiner Extreme"],
  "Archimede": [],
  "Ball": ["Engineer", "Fireman"],
  "Baume & Mercier": ["Clifton", "Riviera"],
  "Benrus": ["Type I", "Type II"],
  "Bremont": ["Supermarine", "Terra Nova"],
  "Carl F. Bucherer": ["Manero", "Patravi"],
  "Chronoswiss": [],
  "Corum": [],
  "Cuervo y Sobrinos": [],
  "Damasko": [],
  "Delma": [],
  "Ebel": [],
  "Eberhard & Co.": [],
  "Edox": [],
  "Eterna": ["KonTiki"],
  "Favre Leuba": [],
  "Fortis": ["Flieger", "Marinemaster"],
  "Franck Muller": ["Cintrée Curvex", "Vanguard"],
  "Frederique Constant": ["Classics", "Highlife", "Slimline"],
  "Hanhart": ["417 ES"],
  "Junghans": ["Max Bill", "Meister"],
  "Laco": ["Navy", "Pilot"],
  "Louis Erard": ["Excellence", "Le Régulateur"],
  "Maurice Lacroix": ["Aikon", "Pontos"],
  "MeisterSinger": [],
  "Mühle-Glashütte": ["29er", "S.A.R. Rescue-Timer"],
  "Nivada Grenchen": ["Antarctic", "Chronomaster"],
  "Norqain": ["Adventure", "Freedom", "Wild ONE"],
  "Ollech & Wajs": [],
  "Pequignet": [],
  "Perrelet": [],
  "Porsche Design": [],
  "Raymond Weil": ["Freelancer", "Millesime"],
  "Reservoir": [],
  "Schwarz Etienne": [],
  "Squale": ["1521", "20 Atmos"],
  "Stowa": ["Antea", "Flieger", "Marine"],
  "Titoni": [],
  "Tutima": ["M2", "Patria"],
  "U-Boat": [],
  "Union Glashütte": [],
  "Universal Genève": ["Compax", "Polerouter"],
  "Vulcain": [],
  "Zodiac": ["Super Sea Wolf"],
  "ZRC": [],
  "Chanel": [],
  "Chaumet": [],
  "Dior": [],
  "Fabergé": [],
  "Gucci": [],
  "Harry Winston": [],
  "Jacob & Co.": [],
  "Louis Vuitton": [],
  "Tiffany & Co.": [],
  "Van Cleef & Arpels": [],
  "Akrivia": [],
  "Andersen Genève": [],
  "Andreas Strehler": [],
  "Angelus": [],
  "Antoine Preziuso": [],
  "Armin Strom": [],
  "Arnold & Son": [],
  "ArtyA": [],
  "Atelier de Chronométrie": [],
  "Auffret Paris": [],
  "Berneron": [],
  "Bianchet": [],
  "Biver": [],
  "Bovet": [],
  "Charles Frodsham": [],
  "Charles Girardier": [],
  "Christiaan van der Klaauw": [],
  "Cyrus": [],
  "Czapek & Cie.": ["Antarctique", "Quai des Bergues"],
  "Daniel Roth": [],
  "David Candaux": [],
  "De Bethune": [],
  "F.P. Journe": ["Chronomètre Bleu", "Octa"],
  "Ferdinand Berthoud": [],
  "Garrick": [],
  "Genus": [],
  "Greubel Forsey": ["Balancier"],
  "Grönefeld": [],
  "Gérald Charles": [],
  "Gérald Genta": [],
  "Habring²": [],
  "Hajime Asaoka": [],
  "Haldimann": [],
  "Hautlence": [],
  "HYT": [],
  "J.N. Shapiro": [],
  "Kari Voutilainen": [],
  "Kikuchi Nakagawa": [],
  "Krayon": [],
  "Kudoke": [],
  "Lang & Heyne": [],
  "Laurent Ferrier": ["Classic", "Sport Auto"],
  "Lederer": [],
  "Louis Moinet": [],
  "Ludovic Ballouard": [],
  "Manufacture Royale": [],
  "MB&F": ["Horological Machine", "Legacy Machine"],
  "Moritz Grossmann": [],
  "Naoya Hida & Co.": [],
  "Petermann Bédat": [],
  "Philippe Dufour": [],
  "Raúl Pagès": [],
  "Renaud Tixier": [],
  "Ressence": ["Type 1", "Type 3"],
  "Roger W. Smith": [],
  "Romain Gauthier": [],
  "Sarpaneva": [],
  "Simon Brette": [],
  "Singer Reimagined": [],
  "Speake-Marin": [],
  "Sylvain Pinaud": [],
  "Trilobe": [],
  "Urban Jürgensen": [],
  "Urwerk": ["UR-100", "UR-220"],
  "Vianney Halter": [],
  "anOrdain": [],
  "Arcanaut": [],
  "Atelier Wen": ["Perception"],
  "Beda'a": [],
  "Behrens": [],
  "Bravur": [],
  "Brellum": [],
  "Carl Suchy & Söhne": [],
  "De Rijke & Co.": [],
  "Farer": ["Aqua Compressor", "Lander"],
  "Fears": ["Brunswick"],
  "Fleming": [],
  "Formex": ["Essence", "Reef"],
  "Holthinrichs": [],
  "Horage": [],
  "ID Genève": [],
  "Isotope": [],
  "Kollokium": [],
  "Laine": [],
  "Laventure": [],
  "Linde Werdelin": [],
  "Lundis Bleus": [],
  "M.A.D.Editions": [],
  "MAEN": [],
  "Minase": [],
  "MING": [],
  "MONTA": [],
  "Oak & Oscar": [],
  "Ochs und Junior": [],
  "Ophion": [],
  "Otsuka Lotec": [],
  "Paulin": [],
  "RGM": [],
  "Sartory Billard": [],
  "Straum": [],
  "Studio Underd0g": [],
  "Toledano & Chan": [],
  "Tornek-Rayville": [],
  "Venezianico": [],
  "Vero": [],
  "Vertex": [],
  "VPC": [],
  "Weiss": [],
  "William Wood": [],
  "Yema": ["Superman", "Navygraf"],
  "Zeitwinkel": [],
  "Aera": [],
  "Albishorn": [],
  "Alto": [],
  "Amida": [],
  "Anoma": ["A1"],
  "Atelier Jalaper": [],
  "Bangalore Watch Company": [],
  "Beaubleu": [],
  "Beaucroft": [],
  "BOLDR": [],
  "Brew": ["Metric", "Retrograph", "HP1"],
  "Circula": ["DiveSport", "SuperSport"],
  "Dan Henry": ["1964", "1970"],
  "Dennison": [],
  "Dufrane": [],
  "Dumoreau": [],
  "Earthen": [],
  "Gagà Laboratorio": [],
  "Halios": ["Seaforth", "Universa"],
  "Héron": [],
  "Lorca": [],
  "Lorier": ["Gemini", "Neptune", "Olympia"],
  "Nodus": [],
  "Ocean Crawler": [],
  "RZE": [],
  "Scurfa": [],
  "SpaceOne": [],
  "Trafford Watch Co.": [],
  "Traska": ["Chronograph", "Commuter", "Freediver", "Summiteer", "Venturer"],
  "Unimatic": ["Modello Uno", "Modello Due"],
  "Vaer": ["C5", "D5", "S5"],
  "Vario": [],
  "Wren": ["Diver 38", "Diver One", "Vessel"],
  "Zelos": [],
  "Ikepod": ["Chronopod", "Duopod", "Megapode", "Seapod"],
};

export const watchBrands: string[] = Object.keys(watchCatalog).sort((a, b) => a.localeCompare(b));

export function modelsForBrand(brand: string): string[] {
  const key = watchBrands.find((b) => b.toLowerCase() === brand.trim().toLowerCase());
  return key ? [...watchCatalog[key]].sort((a, b) => a.localeCompare(b)) : [];
}

// Other common spellings of catalog brands.
const BRAND_ALIASES: Record<string, string> = {
  bvlgari: "Bulgari",
  "iwc schaffhausen": "IWC",
  "nomos glashütte": "Nomos",
  "nomos glashutte": "Nomos",
  "h. moser & cie.": "H. Moser & Cie",
  "h moser": "H. Moser & Cie",
  "rexhep rexhepi": "Akrivia",
  "jacob & co": "Jacob & Co.",
  "tiffany": "Tiffany & Co.",
  "bell and ross": "Bell & Ross",
  "fp journe": "F.P. Journe",
  "lange": "A. Lange & Söhne",
  "a. lange & sohne": "A. Lange & Söhne",
};

// Returns the catalog's spelling for a typed brand, or the brand as typed.
export function canonicalBrand(brand: string): string {
  const typed = brand.trim().toLowerCase();
  return watchBrands.find((b) => b.toLowerCase() === typed) ?? BRAND_ALIASES[typed] ?? brand;
}
