// Brands and model families for the Add Watch dropdowns.
// To add a brand or model, add it here (alphabetical order is applied automatically).
// People can still type any brand/model that isn't listed.

export const watchCatalog: Record<string, string[]> = {
  "A. Lange & Söhne": ["1815", "Datograph", "Lange 1", "Odysseus", "Saxonia", "Zeitwerk"],
  "Audemars Piguet": ["Code 11.59", "Royal Oak", "Royal Oak Chronograph", "Royal Oak Jumbo", "Royal Oak Offshore"],
  Awake: ["Mission to Earth", "Mission to Space"],
  Baltic: ["Aquascaphe", "Bicompax", "HMS 002", "MR01"],
  "Bell & Ross": ["BR 03", "BR 05", "BR-X5"],
  Blancpain: ["Fifty Fathoms", "Fifty Fathoms Bathyscaphe", "Villeret"],
  Breguet: ["Classique", "Marine", "Type XX"],
  Breitling: ["Avenger", "Chronomat", "Navitimer", "Premier", "Superocean", "Superocean Heritage", "Top Time"],
  Bulgari: ["Bulgari Bulgari", "Octo Finissimo", "Serpenti"],
  Cartier: ["Ballon Bleu", "Panthère", "Pasha", "Santos", "Santos-Dumont", "Tank Française", "Tank Louis", "Tank Must"],
  "Casio G-Shock": ["DW-5600", "GA-2100", "GMW-B5000", "MR-G"],
  Chopard: ["Alpine Eagle", "Happy Sport", "L.U.C", "Mille Miglia"],
  "Christopher Ward": ["C1", "C60 Trident", "C63 Sealander", "The Twelve"],
  Citizen: ["Eco-Drive", "Promaster", "Tsuyosa"],
  Doxa: ["SUB 200", "SUB 300", "SUB 300T"],
  "Echo/Neutra": ["Averau", "Rivanera"],
  "Furlan Marri": ["Disco Volante", "Mechaquartz", "Tasti Tondi"],
  "Girard-Perregaux": ["Laureato", "Laureato Absolute"],
  "Grand Seiko": ["Evolution 9", "Heritage", "Snowflake (SBGA211)", "Sport", "White Birch (SLGH005)"],
  "H. Moser & Cie": ["Endeavour", "Pioneer", "Streamliner"],
  Hamilton: ["Jazzmaster", "Khaki Aviation", "Khaki Field", "Khaki Field Mechanical", "Ventura"],
  Hermès: ["Arceau", "H08", "Heure H"],
  Hublot: ["Big Bang", "Classic Fusion", "Spirit of Big Bang"],
  IWC: ["Big Pilot", "Ingenieur", "Pilot's Watch", "Portofino", "Portugieser", "Aquatimer"],
  "Jaeger-LeCoultre": ["Master Control", "Polaris", "Reverso", "Rendez-Vous"],
  "Konstantin Chaykin": ["Joker", "Wristmon"],
  "Kurono Tokyo": ["Bunkyo", "Chronograph", "Grand Mori", "Toki"],
  Longines: ["Conquest", "HydroConquest", "Legend Diver", "Master Collection", "Spirit", "Spirit Flyback", "Spirit Zulu Time"],
  Mido: ["Commander", "Multifort", "Ocean Star"],
  Montblanc: ["1858", "Star Legacy", "TimeWalker"],
  Nomos: ["Ahoi", "Club", "Metro", "Orion", "Tangente"],
  Omega: ["Aqua Terra", "Constellation", "De Ville", "Railmaster", "Seamaster 300M", "Seamaster Planet Ocean", "Speedmaster Moonwatch", "Speedmaster Racing"],
  Oris: ["Aquis", "Big Crown Pointer Date", "Divers Sixty-Five", "ProPilot"],
  Panerai: ["Luminor", "Luminor Due", "Radiomir", "Submersible"],
  "Patek Philippe": ["Aquanaut", "Calatrava", "Complications", "Grand Complications", "Nautilus", "Twenty~4"],
  Rado: ["Captain Cook", "Centrix", "True Square"],
  "Richard Mille": ["RM 011", "RM 035", "RM 67-01"],
  Rolex: ["Air-King", "Cosmograph Daytona", "Datejust 36", "Datejust 41", "Day-Date 40", "Explorer", "Explorer II", "GMT-Master II", "Land-Dweller", "Oyster Perpetual", "Sea-Dweller", "Sky-Dweller", "Submariner", "Submariner Date", "Yacht-Master"],
  Seiko: ["5 Sports", "Alpinist", "Presage", "Prospex", "Prospex Turtle"],
  Serica: ["4512 Field Chronometer", "5303 Diver", "8315 Chronograph"],
  Sinn: ["104", "556", "EZM 3"],
  Swatch: ["MoonSwatch", "Scuba Fifty Fathoms", "Sistem51"],
  "TAG Heuer": ["Aquaracer", "Carrera", "Formula 1", "Monaco"],
  Tissot: ["Gentleman", "PRX", "Seastar", "Visodate"],
  Tudor: ["1926", "Black Bay", "Black Bay 54", "Black Bay 58", "Black Bay 58 GMT", "Black Bay Chrono", "Black Bay GMT", "Black Bay Pro", "Pelagos", "Pelagos 39", "Ranger", "Royal"],
  "Ulysse Nardin": ["Diver", "Freak", "Marine"],
  "Vacheron Constantin": ["Fiftysix", "Historiques 222", "Overseas", "Patrimony", "Traditionnelle"],
  Zenith: ["Chronomaster Original", "Chronomaster Sport", "Defy", "Pilot"],
  // Added from the luxury & microbrand brand reference (Oct 2026). Models can be typed in if not listed.
  "Credor": ["Eichi", "Linealight"],
  "Glashütte Original": ["PanoMaticLunar", "SeaQ", "Senator"],
  "Jaquet Droz": ["Grande Seconde", "Petite Heure Minute"],
  "Parmigiani Fleurier": ["Kalpa", "Tonda PF"],
  "Piaget": ["Altiplano", "Polo", "Polo 79"],
  "Roger Dubuis": ["Excalibur"],
  "Accutron": ["DNA", "Spaceview"],
  "Airain": ["Type 20", "Sous-Marine"],
  "Alpina": ["Alpiner Extreme"],
  "Archimede": ["OutDoor", "Pilot", "SportTaucher", "1950", "Marine", "Klassik"],
  "Ball": ["Engineer", "Fireman"],
  "Baume & Mercier": ["Clifton", "Riviera"],
  "Benrus": ["Type I", "Type II"],
  "Bremont": ["Supermarine", "Terra Nova"],
  "Carl F. Bucherer": ["Manero", "Patravi"],
  "Chronoswiss": ["Regulator", "Flying Regulator", "Delphis", "Classic", "Artist Collection", "Tourbillon", "Lunar Chronograph", "Q-Repeater"],
  "Corum": ["Admiral", "Golden Bridge", "Bubble", "Heritage"],
  "Cuervo y Sobrinos": ["Historiador", "Prominente", "Robusto", "Hemingway", "Primera Dama", "Esplendidos", "Churchill", "Buceador"],
  "Damasko": ["DA", "DC", "DK", "DS", "DSub", "DF"],
  "Delma": ["Blue Shark", "Shell Star", "Commodore", "Oceanmaster", "Klondike", "Rialto"],
  "Ebel": ["Sport Classic", "1911", "Wave", "Discovery", "Brasilia", "Beluga"],
  "Eberhard & Co.": ["Chrono 4", "Scafograf", "Extra-Fort", "Contograf", "8 Jours", "Tazio Nuvolari", "Scientigraf", "Gilda"],
  "Edox": ["CO-1", "Neptunian", "Delfin", "Grand Ocean", "Hydro-Sub", "Skydiver", "Chronorally", "Sportsman"],
  "Eterna": ["KonTiki"],
  "Favre Leuba": ["Raider", "Chief", "Bivouac", "Sea Sky", "Deep Blue", "Bathy", "Harpoon"],
  "Fortis": ["Flieger", "Marinemaster"],
  "Franck Muller": ["Cintrée Curvex", "Vanguard"],
  "Frederique Constant": ["Classics", "Highlife", "Slimline"],
  "Hanhart": ["417 ES"],
  "Junghans": ["Max Bill", "Meister"],
  "Laco": ["Navy", "Pilot"],
  "Louis Erard": ["Excellence", "Le Régulateur"],
  "Maurice Lacroix": ["Aikon", "Pontos"],
  "MeisterSinger": ["No. 01", "No. 03", "Neo", "Pangaea", "Perigraph", "Lunascope", "Stratoscope", "Primatic"],
  "Mühle-Glashütte": ["29er", "S.A.R. Rescue-Timer"],
  "Nivada Grenchen": ["Antarctic", "Chronomaster"],
  "Norqain": ["Adventure", "Freedom", "Wild ONE"],
  "Ollech & Wajs": ["C-1000", "M-110", "OceanGraph", "P-101", "P-104", "Astrochron", "Navichron", "RallyChron"],
  "Pequignet": ["Rue Royale", "Royale", "Moorea", "Attitude", "Concorde"],
  "Perrelet": ["Turbine", "Lab Peripheral", "Weekend", "First Class", "Seacraft"],
  "Porsche Design": ["Chronograph 1", "1919", "Chronotimer", "Monobloc Actuator"],
  "Raymond Weil": ["Freelancer", "Millesime"],
  "Reservoir": ["Longbridge", "Supercharged", "GT Tour", "Hydrosphere", "Airfight", "Kanister", "Battlefield", "Sonomaster"],
  "Schwarz Etienne": ["Roma", "1902", "Roswell", "Geometry", "Fiji"],
  "Squale": ["1521", "20 Atmos"],
  "Stowa": ["Antea", "Flieger", "Marine"],
  "Titoni": ["Seascoper", "Airmaster", "Master Series", "Cosmo", "Line 1919", "Heritage", "Impetus", "Space Star"],
  "Tutima": ["M2", "Patria"],
  "U-Boat": ["Chimera", "Capsoil", "Classico", "Darkmoon", "Sommerso"],
  "Union Glashütte": ["Belisar", "Noramis", "Averin", "1893", "Viro", "Seris"],
  "Universal Genève": ["Compax", "Polerouter"],
  "Vulcain": ["Cricket", "Monopusher", "Skindiver", "50s Presidents", "Grand Prix", "Nautical"],
  "Zodiac": ["Super Sea Wolf"],
  "ZRC": ["Grands Fonds", "Securicode"],
  "Chanel": ["J12", "Première", "Boy·Friend", "Code Coco", "Monsieur de Chanel"],
  "Chaumet": ["Hortensia", "Liens", "Joséphine", "Class One", "Dandy"],
  "Dior": ["Chiffre Rouge", "La D de Dior", "Gem Dior", "Grand Bal"],
  "Fabergé": ["Visionnaire", "Altruist", "Compliquée", "Dalliance", "Flirt"],
  "Gucci": ["G-Timeless", "25H", "Dive", "Interlocking", "Grip"],
  "Harry Winston": ["Ocean", "Premier", "Midnight", "Emerald", "Avenue", "Opus", "Histoire de Tourbillon"],
  "Jacob & Co.": ["Astronomia", "Epic X", "Bugatti", "Opera", "Five Time Zone", "Twin Turbo", "Brilliant", "Palatial"],
  "Louis Vuitton": ["Tambour", "Escale", "Tambour Taiko", "Monterey", "Tambour Convergence"],
  "Tiffany & Co.": ["Atlas", "CT60", "East West", "Cocktail"],
  "Van Cleef & Arpels": ["Lady Arpels", "Midnight", "Pierre Arpels", "Charms", "Cadenas"],
  "Akrivia": ["AK-06", "Chronomètre Contemporain"],
  "Andersen Genève": ["Jumping Hours", "Tempus Terrae", "Communication", "Montre à Tact", "Quotidiana", "Rattrapante Mondiale"],
  "Andreas Strehler": ["Sauterelle", "Papillon", "Lune Exacte", "Trans-Axial Tourbillon", "Cocon"],
  "Angelus": ["Chronodate", "U10", "U30", "U40", "Flying Tourbillon", "Instrument de Vitesse", "Tinkler 1958", "Chronographe Télémètre"],
  "Antoine Preziuso": ["Tourbillon of Tourbillons", "Grand Tourbillon Sport (GTS)", "Hours of Love", "TransWorld", "Fire Fly"],
  "Armin Strom": ["System 78", "Resonance", "Mirrored Force Resonance", "Gravity Equal Force", "One Week", "Orbit", "Tribute 1", "Dual Time GMT Resonance"],
  "Arnold & Son": ["Perpetual Moon", "Luna Magna", "Globetrotter", "Nebula", "Time Pyramid", "Ultrathin Tourbillon", "Constant Force", "Longitude"],
  "ArtyA": ["Son of Earth", "Son of Gears", "Son of Sound", "Son of a Gun", "Race", "Purity", "Luminity", "Complexity"],
  "Atelier de Chronométrie": ["AdC #2", "AdC #3", "AdC #4", "AdC #8", "AdC #88"],
  "Auffret Paris": ["Tourbillon à Paris", "Tourbillon Grand Sport"],
  "Berneron": ["Mirage", "Quantième Annuel"],
  "Bianchet": ["UltraFino"],
  "Biver": ["Carillon Tourbillon", "Automatique"],
  "Bovet": ["Fleurier", "Dimier", "Récital", "Virtuoso", "19Thirty", "Bovet by Pininfarina"],
  "Charles Frodsham": ["Double Impulse Chronometer"],
  "Charles Girardier": ["1809", "Magic 8", "Tourbillon Signature Mystérieuse", "Synchronaut"],
  "Christiaan van der Klaauw": ["Planetarium", "Real Moon"],
  "Cyrus": ["Klepcys", "Dominion", "Etheral"],
  "Czapek & Cie.": ["Antarctique", "Quai des Bergues"],
  "Daniel Roth": ["Tourbillon", "Extra Plat"],
  "David Candaux": ["DC1", "DC6", "DC7", "DC12 Maverik"],
  "De Bethune": ["DB25", "DB27", "DB28", "DB28XS", "DB29", "DB Kind of Two", "DB Eight", "DBD"],
  "F.P. Journe": ["Chronomètre Bleu", "Octa"],
  "Ferdinand Berthoud": ["Chronomètre FB 1", "Chronomètre FB 2", "Chronomètre FB 3"],
  "Garrick": ["S1", "S2", "S3", "S4", "S6", "Portsmouth", "Norfolk", "Shaftesbury"],
  "Genus": ["GNS 1.1", "GNS 1.2", "GNS2"],
  "Greubel Forsey": ["Balancier"],
  "Grönefeld": ["1941 Remontoire", "1941 Principia", "1941 Grönograaf", "1941 Quadrivium", "1944 Tanfana", "1969 DeltaWorks", "Parallax Tourbillon", "Decennium Tourbillon"],
  "Gérald Charles": ["Maestro", "Masterlink"],
  "Gérald Genta": ["Geneva", "Gentissima", "Arena"],
  "Habring²": ["Doppel", "Erwin", "Felix", "Foudroyante", "Josef"],
  "Hajime Asaoka": ["Tsunami", "Tourbillon", "Project T", "Chronograph"],
  "Haldimann": ["H2 Flying Resonance", "H9 Reduction", "H11", "H12"],
  "Hautlence": ["Vagabonde", "Retrovision", "Sphere", "Linear", "Kubera", "Helix", "HLXX"],
  "HYT": ["Hastroid", "Moon Runner", "Soonow", "H1", "H2", "H5"],
  "J.N. Shapiro": ["Infinity Series", "Resurgence"],
  "Kari Voutilainen": ["Vingt-8", "28SC", "Observatoire", "Masterpiece", "Chronomètre 27"],
  "Kikuchi Nakagawa": ["Murakumo", "Ichimonji"],
  "Krayon": ["Everywhere", "Anywhere"],
  "Kudoke": ["Kudoke 1", "Kudoke 2", "Kudoke 3"],
  "Lang & Heyne": ["Friedrich August I", "König Johann", "König Albert", "Georg", "Moritz", "Anton", "Hektor", "Augustus"],
  "Laurent Ferrier": ["Classic", "Sport Auto"],
  "Lederer": ["CIC 39mm", "CIC 44", "Inverto"],
  "Louis Moinet": ["Memoris", "Space Revolution", "Tempograph", "Starman", "Derrick", "Cosmopolis", "Time to Race"],
  "Ludovic Ballouard": ["Upside Down", "Half Time"],
  "Manufacture Royale": ["The Spirit", "Micromegas", "1770 Voltige", "ADN", "Androgyne", "Opera"],
  "MB&F": ["Horological Machine", "Legacy Machine"],
  "Moritz Grossmann": ["Benu", "Tefnut", "Atum", "200 Jahre"],
  "Naoya Hida & Co.": ["NH Type 1", "NH Type 4", "NH Type 5", "NH Type 6"],
  "Petermann Bédat": ["Reference 1967", "Reference 2941"],
  "Philippe Dufour": ["Simplicity", "Duality", "Grande et Petite Sonnerie"],
  "Raúl Pagès": ["Soberly", "RP1 Régulateur à Détente", "RP2"],
  "Renaud Tixier": ["Monday"],
  "Ressence": ["Type 1", "Type 3"],
  "Roger W. Smith": ["Series One", "Series Two", "Series Three", "Series Four", "Series Five", "Series Six"],
  "Romain Gauthier": ["Prestige", "Logical One", "Insight Micro-Rotor", "C by Romain Gauthier"],
  "Sarpaneva": ["Korona K0", "Korona K1", "Korona K3"],
  "Simon Brette": ["Chronomètre Artisans"],
  "Singer Reimagined": ["Track 1", "Flytrack", "Divetrack", "DualTrack", "1969", "Caballero"],
  "Speake-Marin": ["Openworked", "One & Two Openworked", "Ripples", "Academic", "Piccadilly"],
  "Sylvain Pinaud": ["Origine", "Chronographe Monopoussoir", "Tourbillon 30 Second"],
  "Trilobe": ["Nuit Fantastique", "Les Matinaux", "Une Folle Journée"],
  "Urban Jürgensen": ["UJ-1 Tourbillon", "UJ-2", "UJ-3 Perpetual Calendar"],
  "Urwerk": ["UR-100", "UR-220"],
  "Vianney Halter": ["Antiqua", "Classic", "Trio", "Contemporaine", "Deep Space"],
  "anOrdain": ["Model 1", "Model 2", "Model 3"],
  "Arcanaut": ["Arc II"],
  "Atelier Wen": ["Perception"],
  "Beda'a": ["Eclipse", "Angles"],
  "Behrens": ["Apolar", "Orion One", "Rotary", "Mars Project One", "Ultralight 20G", "Perigee", "Navigraph"],
  "Bravur": ["Scandinavia", "BW003", "Geography"],
  "Brellum": ["Duobox", "Pandial", "Pilot", "Wyvern"],
  "Carl Suchy & Söhne": ["Waltz N°1", "Belvedere"],
  "De Rijke & Co.": ["Amalfi Series", "Capri", "Miffy Moonphase"],
  "Farer": ["Aqua Compressor", "Lander"],
  "Fears": ["Brunswick"],
  "Fleming": ["Series 1"],
  "Formex": ["Essence", "Reef"],
  "Holthinrichs": ["Signature Ornament", "Signature Delft Blue", "Signature Lab Series", "Deconstructed"],
  "Horage": ["Autark", "Supersede", "Lensman", "Tourbillon"],
  "ID Genève": ["Circular 1", "Circular S"],
  "Isotope": ["Hydrium", "GMT 0°", "Rider Jumping Hours"],
  "Kollokium": ["Projekt 01"],
  "Laine": ["V38", "Gelidus 3", "GG3"],
  "Laventure": ["Sous-Marine", "Transatlantique GMT", "Marine", "Automobile"],
  "Linde Werdelin": ["3-Timer", "Oktopus", "SpidoLite", "The One"],
  "Lundis Bleus": ["1100", "Essentielles", "Contemporaines", "Métiers d'Art"],
  "M.A.D.Editions": ["M.A.D.1", "M.A.D.1S", "M.A.D.2"],
  "MAEN": ["Hudson", "Manhattan", "Skymaster", "Greenwich", "Brooklyn", "Classic", "Lunar Classic"],
  "Minase": ["Seven Windows", "Five Windows", "Horizon", "Divido", "HiZ"],
  "MING": ["17 Series", "37 Series", "20 Series", "19 Series", "18 Series", "27 Series", "29 Series", "22 Series"],
  "MONTA": ["Triumph", "Oceanking", "Atlas", "Skyquest", "Noble"],
  "Oak & Oscar": ["Burnham", "Sandford", "Jackson", "Humboldt", "Olmsted"],
  "Ochs und Junior": ["Settimana", "Anno", "Calendario", "Luna Sole", "Selene", "Due Ore", "Mese"],
  "Ophion": ["OPH 960", "OPH 786"],
  "Otsuka Lotec": ["No.5", "No.6", "No.7", "No.7.5"],
  "Paulin": ["Neo", "Neo GMT", "Modul", "Mara Diver"],
  "RGM": ["Pennsylvania Series", "801", "Caliber 20", "Pennsylvania Tourbillon"],
  "Sartory Billard": ["SB01", "SB02", "SB03", "SB04", "SB05", "SB06", "SB07", "SB08"],
  "Straum": ["Jan Mayen"],
  "Studio Underd0g": ["01Series", "02Series", "03Series"],
  "Toledano & Chan": ["B/1", "B/1.2"],
  "Tornek-Rayville": ["TR-900", "TR-660"],
  "Venezianico": ["Redentore", "Nereide", "Arsenale", "Bucintoro"],
  "Vero": ["Open Water", "Workhorse", "Meridian", "Century", "36 Automatic"],
  "Vertex": ["M100", "M60 Aqualion", "MP45"],
  "VPC": ["Type 37HW", "Type 39VM"],
  "Weiss": ["Standard Issue Field Watch", "American Issue Field Watch"],
  "William Wood": ["Triumph", "Valiant", "Day Date", "Historic"],
  "Yema": ["Superman", "Navygraf"],
  "Zeitwinkel": ["081°", "082°", "188°", "273°"],
  "Aera": ["D-1", "P-1", "C-1", "M-1"],
  "Albishorn": ["Maxigraph", "Type 10"],
  "Alto": ["Art 01", "Art 02"],
  "Amida": ["Digitrend"],
  "Anoma": ["A1"],
  "Atelier Jalaper": ["DB5", "Miura", "Type E"],
  "Bangalore Watch Company": ["MACH 1", "Cover Drive", "Apogee", "Peninsula"],
  "Beaubleu": ["Ecce", "Figura", "La Pièce", "Seconde Française", "Flat White", "Union", "Vitruve"],
  "Beaucroft": ["Element", "Seeker", "Signature", "Arc", "Contour"],
  "BOLDR": ["Venture", "Odyssey", "Expedition", "Safari"],
  "Brew": ["Metric", "Retrograph", "HP1"],
  "Circula": ["DiveSport", "SuperSport"],
  "Dan Henry": ["1964", "1970"],
  "Dennison": ["ALD Time Only", "ALD Dual Time", "ALD Mini", "ALD Mini Dual Time"],
  "Dufrane": ["Barton Springs", "Bergstrom", "Waterloo", "Mabry", "Circuit"],
  "Dumoreau": ["DM01", "DM02"],
  "Earthen": ["Summit"],
  "Gagà Laboratorio": ["Labormatic", "Aqualab", "Luce"],
  "Halios": ["Seaforth", "Universa"],
  "Héron": ["Marinor", "Continental", "Gladiateur"],
  "Lorca": ["Model No.1 GMT", "Model No.2 Chronograph"],
  "Lorier": ["Gemini", "Neptune", "Olympia"],
  "Nodus": ["Sector", "Contrail", "Duality", "Retrospect", "Avalon", "Unity", "Sentinel", "Obscura"],
  "Ocean Crawler": ["Core Diver", "Champion Diver", "Field Crawler", "Bolt", "Ocean Navigator", "Dream Diver", "Crawler One"],
  "RZE": ["Resolute", "Endeavour", "Valour", "Fortitude"],
  "Scurfa": ["Diver One", "Treasure Seeker", "Bell Diver"],
  "SpaceOne": ["Jumping Hour", "Tellurium", "WorldTimer"],
  "Trafford Watch Co.": ["Crossroads", "Touring GMT", "Daytripper", "Core"],
  "Traska": ["Chronograph", "Commuter", "Freediver", "Summiteer", "Venturer"],
  "Unimatic": ["Modello Uno", "Modello Due"],
  "Vaer": ["C5", "D5", "S5"],
  "Vario": ["Empire", "1918", "Versa", "Navi", "1945 D12", "Futurist"],
  "Wren": ["Diver 38", "Diver One", "Vessel"],
  "Zelos": ["Hammerhead", "Helmsman", "Swordfish", "Great White", "Blacktip", "Helica", "Thresher", "Comet"],
  "Ikepod": ["Chronopod", "Duopod", "Megapode", "Seapod"],
};

export const watchBrands: string[] = Object.keys(watchCatalog).sort((a, b) => a.localeCompare(b));

export function modelsForBrand(brand: string): string[] {
  const key = watchBrands.find((b) => b.toLowerCase() === brand.trim().toLowerCase());
  return key ? [...watchCatalog[key]].sort((a, b) => a.localeCompare(b)) : [];
}

// Other common spellings of catalog brands.
const BRAND_ALIASES: Record<string, string> = {
  bvlgari: "Bulgari",
  "iwc schaffhausen": "IWC",
  "nomos glashütte": "Nomos",
  "nomos glashutte": "Nomos",
  "h. moser & cie.": "H. Moser & Cie",
  "h moser": "H. Moser & Cie",
  "rexhep rexhepi": "Akrivia",
  "jacob & co": "Jacob & Co.",
  "tiffany": "Tiffany & Co.",
  "bell and ross": "Bell & Ross",
  "fp journe": "F.P. Journe",
  "lange": "A. Lange & Söhne",
  "a. lange & sohne": "A. Lange & Söhne",
};

// Returns the catalog's spelling for a typed brand, or the brand as typed.
export function canonicalBrand(brand: string): string {
  const typed = brand.trim().toLowerCase();
  return watchBrands.find((b) => b.toLowerCase() === typed) ?? BRAND_ALIASES[typed] ?? brand;
}
